[package]
name = "parakesh-ui"
version = "0.1.1"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["qr_code"] }
parakesh-common = { version = "0.1.1", path = "../parakesh-common" }
tokio = "1.44.2"
