[package]
name = "parakesh"
version = "0.2.0"
description = "Simple Cashu wallet, console UI, built on CDK, event-based invocations"
license = "MIT"
edition = "2021"

[dependencies]
parakesh-common = { version = "0.2.0", path = "../parakesh-common" }
tokio = "1.44.1"

